### ISSUE TITLE
Different types of cards do not align correctly

### ISSUE THREAD

**Issue by arsaboo** [kuuji/button-card#11]
So, I tried to add two different types of button cards as follows:
```yaml
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                color_type: blank-card
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:volume-plus
                action: service
                service:
                  domain: media_player
                  action: volume_up
                  data:
                    entity_id: media_player.family_room_2
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:volume-minus
                action: service
                service:
                  domain: media_player
                  action: volume_down
                  data:
                    entity_id: media_player.family_room_2
              - type: "custom:button-card"
                entity: sensor.sonos_volume
                color_type: card
                show_state: true
                color: rgb(223, 255, 97)
                action: more_info
              - type: "custom:button-card"
                color_type: blank-card
```
However, they don't align well. 
![image](https://user-images.githubusercontent.com/18319734/45113711-19cd8c00-b119-11e8-84a5-fd22c7b1b611.png)

Notice how the state card is slightly smaller than the other cards.

**Comment by kuuji** [comment]
The size depends on the what the card includes. I did that intentionally because I assumed it would look better in most cases (fix sized could cause issues with bigger or smaller element).

There might be some CSS trick to do something dynamic but I'm not comfortable enough with CSS to do that sort of wizardry.

I would suggest overriding that by setting a fixed height using the `style` setting.

```yaml
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                color_type: blank-card
				style:
					- height: 60px
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:volume-plus
				style:
					- height: 60px
                action: service
                service:
                  domain: media_player
                  action: volume_up
                  data:
                    entity_id: media_player.family_room_2
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:volume-minus
				style:
					- height: 60px
                action: service
                service:
                  domain: media_player
                  action: volume_down
                  data:
                    entity_id: media_player.family_room_2
              - type: "custom:button-card"
                entity: sensor.sonos_volume
                color_type: card
				style:
					- height: 60px
                show_state: true
                color: rgb(223, 255, 97)
                action: more_info
              - type: "custom:button-card"
                color_type: blank-card
				style:
					- height: 60px
```
