### ISSUE TITLE
Color based on attribute

### ISSUE THREAD

**Issue by jaburges** [kuuji/button-card#16]
Covered my whole lovelace UI in buttons to control the house - LOVE IT! Thanks

Would it be possible to have a color_trigger based on attribute? I'm thinking of primarily a fan
 (so if the speed = 'low') then the color of the button would change then? 
If you had 3 buttons (low, medium, high) 
you could set instead of off or on (as the fan doesnt have off or on) color_trigger based on the attribute of the fan speed. 

```
- type: "custom:button-card"
                entity: switch.bedroom_fan
                size: 48px
                icon: mdi:fan
                name: Low
                action: service
                service:
                  domain: fan
                  action: set_speed
                  data:
                    entity_id: fan.bedroom_fan
                    speed: low
                color_type: card
                color_off: rgb(68, 70, 73)
                color: rgb(1, 121, 116)
                **color_trigger: 
                  value_template:  "{{ is_state('fan.attributes.speed', 'low')}}"**
```
I am being a little lazy here as could make switches for each speed, but i'm thinking of also those folks that use it for tv remotes (ie light up the xbox logo when that attribute is set)?

**Comment by jaburges** [comment]
Thanks buddy, dont know how niche the request is - but also thought could be cool to show buttons based on sensor values? temp / color. Ultimately anything that isn't straight on/off

I can also create a switch for each button (switch.fan_slow_speed) which would also solve the problem without any work on the UI side.

Appreciate all your work!

**Comment by kuuji** [comment]
> Appreciate all your work!

Thanks mate.

> Thanks buddy, dont know how niche the request is - but also thought could be cool to show buttons based on sensor values? temp / color. Ultimately anything that isn't straight on/off

I have both custom state and custom color per state working locally.

I'll show you how the yaml look like and you can give me some feedback ;).
For custom icon per state I think it'll require to change more things but that should be possible eventually as well.

**Comment by kuuji** [comment]
@jaburges 	

```
              - type: "custom:button-card"
                entity: input_select.cube_mode
                icon: mdi:cube
                action: service
                show_state: true
                state:
                  - value: 'sleeping'
                    color: var(--disabled-text-color)
                  - value: 'media'
                    color: rgb(5, 147, 255)
                  - value: 'light'
                    color: rgb(189, 255, 5)
```

That's a button for a select input. It calls a service to select the next option when you click on it. That was already possible before, now the new thing is the state parameter. Here I defined 3 states with 3 values and 3 different colors.

What do you think?
