### ISSUE TITLE
Name of entity

### ISSUE THREAD

**Issue by claudioita** [kuuji/button-card#2]
Hi, can you add the name of entity_id, I just put 3 in a horizontalk stack and ...

![cattura](https://user-images.githubusercontent.com/23485319/44671547-1dc92200-aa26-11e8-87bd-b02cb64c65fc.JPG)

**Comment by kuuji** [comment]
Hey @claudioita ! Thanks for your suggestion.
For my use case I didn't need the entity name but it's definitely something I can add. 
Where would you want it?

As for your color issue, I changed the color based on the state of the entity. I use the color you specify if the entity state is `on`. If it's anything but `on` it'll be grey. Also something I could allow to customize in a future release.

**Comment by matisaul** [comment]
@kuuji Great feature! It would be nice to have a custom name of the entity on "button-center" space, or maybe user could assign the position using top, left options. Like:

```
type: "custom:button-card"
entity: switch.ac
icon: mdi:air-conditioner
color: rgb(28, 128, 199)
title: "My A/C"
position:
  left: 40%
  top: 80%
```

 Thanks!
