### ISSUE TITLE
Correct syntax for turning off all lights

### ISSUE THREAD

**Issue by xbmcnut** [kuuji/button-card#24]
Hi there,

Trying to create a button to turn off all lights. Toggle works but off course turns on all lights that are off in the opposite state which is undesirable. Just want to turn off all lights when pushed and icon tracks all lights state. Below is not working.

```
              - type: "custom:button-card"
                # entity: group.all_lights
                icon: mdi:lightbulb-on-outline
                color: rgb(255, 255, 47)
                action: service
                service:
                  domain: light
                  action: homeassistant.turn_off
                  data:
                    entity_id: group.all_lights
                name: All Lights
```

Any help would be appreciated

**Comment by xbmcnut** [comment]
Disregard. This works.

```
                action: service
                service:
                  domain: homeassistant
                  action: turn_off
                  data:
                    entity_id: group.all_lights
```
