### ISSUE TITLE
[FR] Two icon states

### ISSUE THREAD

**Issue by xbmcnut** [kuuji/button-card#25]
Hi,

I'd love to be able to track my garage door using one of your buttons and use one icon `mdi:garage` (green) when closed and another icon `mdi:garage-open` (red), when open. Very high WAF.

Is that doable?

**Comment by kuuji** [comment]
@xbmcnut I have a working version of a new feature that will allow you to do different color for different state but nothing for different icons yet. 

For now you can probably have two buttons and control the display with a conditional card. Not ideal but that'd work.

**Comment by xbmcnut** [comment]
That is great, thank you. The two color icon option would be great for now. I'll keep and eye out.

**Comment by kuuji** [comment]
Hey @xbmcnut! Here's what I have

```
              - type: "custom:button-card"
                entity: input_select.cube_mode
                icon: mdi:cube
                action: service
                show_state: true
                state:
                  - value: 'sleeping'
                    color: var(--disabled-text-color)
                  - value: 'media'
                    color: rgb(5, 147, 255)
                  - value: 'light'
                    color: rgb(189, 255, 5)
```

That's a button for a select input. It calls a service to select the next option when you click on it. That was already possible before, now the new thing is the state parameter. Here I defined 3 states with 3 values and 3 different colors.

What do you think?

**Comment by xbmcnut** [comment]
That's above and beyond. Awesome! That will allow for many variables and is a welcomed addition. Thank you. I look forward to trying it out.

**Comment by kuuji** [comment]
@xbmcnut It's released!

**Comment by kuuji** [comment]
I renamed your issue. I'm gonna keep it around for the icon part of it. It'll require a bit more work.

**Comment by xbmcnut** [comment]
I add the following to test.

```
            - type: "custom:button-card"
              entity: input_select.pool_pump
              icon: mdi:cube
              action: service
              show_state: true
              state:
                - value: 'Auto'
                  color: var(--disabled-text-color)
                - value: 'On'
                  color: rgb(5, 147, 255)
                - value: 'Off'
                  color: rgb(189, 255, 5)
```
Am I using it correctly as I get the following error.


```
http://ipofhass:8123/local/lovelace/button-card.js?v=0.0.2:165:46 Uncaught TypeError: Cannot read property 'domain' of undefined
11:55 AM components/system_log/__init__.py (ERROR)
```
