### ISSUE TITLE
Toggles all items in group instead of group

### ISSUE THREAD

**Issue by wbilger** [kuuji/button-card#30]
If I use a group entity with the button, it toggles all items in the group, instead of toggling the group.
For example, if one light in the group is on and all others are off, one light will turn back off, and all others will turn on.

**Comment by kuuji** [comment]
unfortunately @wbilger that's how the toggle service works. 

If you want to do this you'll have to do it through a custom switch. Let me show you what I do on my setup

```yaml
- platform: template
  switches:
    home_lights:
      value_template: "{{ is_state('group.home_lights', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.home_lights
      turn_off: 
        service: homeassistant.turn_off
        entity_id: group.home_lights
```
