### ISSUE TITLE
Using action: sevice brakes color customizing

### ISSUE THREAD

**Issue by radinsky** [kuuji/button-card#32]
When using  'action: service' the "color" (color on) parameter is not working

**Comment by kuuji** [comment]
@radinsky Can you show me your config? Thanks

**Comment by radinsky** [comment]
sure,
This one is working with action to trigger my scene (but the color off is not working):
```
          - type: "custom:button-card"
            action: service
            service:
              domain: scene
              action: turn_on
              data:
                entity_id: scene.kitchen_entry_off
            icon: mdi:lightbulb
            color: auto
            color_type: card
            default_color: "#997701"
            color_off: "#555555"
            name: Off
            style:
              - font-size: 12px
              - font-weight: bold
              - text-transform: none

```
The button trigger the scene but has a wrong color:
![image](https://user-images.githubusercontent.com/4540268/48074851-84b74400-e1ea-11e8-8421-8c80c1c5eccf.png)



This one with removed "action" section:
```
          - type: "custom:button-card"
            entity: scene.kitchen_entry_off
            icon: mdi:lightbulb
            color: auto
            color_type: card
            default_color: "#997701"
            color_off: "#555555"
            name: Off
            style:
              - font-size: 12px
              - font-weight: bold
              - text-transform: none
```
it makes this button with correct color (but the scene is not triggering):
![image](https://user-images.githubusercontent.com/4540268/48074742-491c7a00-e1ea-11e8-888a-2363e65a6594.png)

**Comment by kuuji** [comment]
You do not have an entity on the first one. So `color: auto` doesn't know which color to pick.
You'll need an entity with a color attribute for `color: auto` to work.

Also for color_off to work, the entity needs to have an `off` state. So a scene might not have that.

I'd advise using my new state attribute to do what you want to do. You'll need to set the entity to the scene so that you can use the different attributes.

I don't recall if a scene entity has a color attribute, if it does, you can use `color: auto` so that you don't have to specify the color.


```
                state:
                  - value: 'scening'
                    color: "#997701"

```

This is just an example off the top of my head, I don't have hass available to try this right now.

**Comment by radinsky** [comment]
Ok, adding the "entity" to the first one is solving the issue. Thanks!

```
          - type: "custom:button-card"
            entity: scene.kitchen_entry_off #for the auto color
            action: service
            service:
              domain: scene
              action: turn_on
              data:
                entity_id: scene.kitchen_entry_off
            icon: mdi:lightbulb
            color: auto
            color_type: card
            default_color: "#997701"
            color_off: "#555555"
            name: Off
            style:
              - font-size: 12px
              - font-weight: bold
              - text-transform: none
```
![image](https://user-images.githubusercontent.com/4540268/48076708-75d29080-e1ee-11e8-9bec-5390ecf3c5fb.png)
