### ISSUE TITLE
Removing Shadow on Button

### ISSUE THREAD

**Issue by JCGrzywna** [kuuji/button-card#33]
Is there any way to remove the shadow around the button?

**Comment by iantrich** [comment]
The `style` option says you can already do this, but looking at the code, except for the blank button, style is actually applied to the button element. Perhaps we could have a `button_style` and `card_style`
Once you have `card_style` you just need to then add
```yaml
card_style:
  - box-shadow: none
  - background: transparent
```
