### ISSUE TITLE
Change icon based on state

### ISSUE THREAD

**Issue by brianhanifin** [kuuji/button-card#38]
I used a script to toggle the state of my garage door and the color changes as expected, but I was hoping that I could also change the icon to indicate state.

Here is my example code:
```
          - type: custom:button-card
            action: service
            color_type: card
            color: rgb(66, 134, 244)
            entity: cover.garage_door
            icon: mdi:garage
            service:
              domain: script
              action: turn_on
              data:
                entity_id: script.toggle_garage_door
            show_state: true
            state:
              - value: 'closed'
                color: var(--disabled-text-color)
                icon: mdi:garage
              - value: 'closing'
                color: rgb(66, 134, 244)
                icon: mdi:garage-open
              - value: 'open'
                color: rgb(66, 134, 244)
                icon: mdi:garage-open
              - value: 'opening'
                color: rgb(66, 134, 244)
                icon: mdi:garage-open
```
