### ISSUE TITLE
possible to change button color

### ISSUE THREAD

**Issue by jaburges** [kuuji/button-card#5]
Hi there, 
working my way through all the lovelace UI docs, and stumbled across your button card (super handy so thank you)
Is it possible to set the color, but instead of it changing the mdi icon, it changes the whole button?

**Comment by kuuji** [comment]
Hey! Thanks for the suggestion! I'll add an option to do that ;)

**Comment by jaburges** [comment]
not sure if this helps - but here is an example of the custom-tiles a lot of people used pre-lovelace:

```
input_text.remote_down:
  custom_ui_state_card: state-card-tiles
  config:
    columns: 12
    cell_height: 48px
    cell_width: 48px
    gap: 10px
    text_size: 1em
    color: '#555B65'
    color_on: '#0179d8'
    color_off: '#555B65'
    entities:
      - entity: script.lr_tvvolumeup
        icon: mdi:volume-plus
        column_span: 3
      - entity: script.lr_tvvolumedown
        icon: mdi:volume-minus
        column_span: 3
```
