### ISSUE TITLE
Light group does not change icon color

### ISSUE THREAD

**Issue by tatunts** [kuuji/button-card#6]
Hello everyone! Great custom ui, just love it! Thanks for the time and effort.

I was wondering why this happens here: only the light group does not changes the color, like this:

![image](https://user-images.githubusercontent.com/25224882/44947983-f8ecfa00-adeb-11e8-9dfb-8a1c1d2cdc99.png)

Code:

```yaml
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: light.entrada
            icon: mdi:lightbulb
            action: toggle
            size: 60%
            color: rgb(211, 47, 47)
            name: Entrada
            style:
              - text-transform: none
          - type: custom:button-card
            entity: light.luzes_principais_cozinha
            icon: mdi:lightbulb
            action: toggle
            size: 60%
            color: rgb(211, 47, 47)
            name: Cozinha
            style:
              - text-transform: none
          - type: custom:button-card
            entity: light.area_servico
            icon: mdi:lightbulb
            action: toggle
            size: 60%
            color: rgb(211, 47, 47)
            name: Area serviço
            style:
              - text-transform: none
```

Thanks.
